// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Jh1gBPnFxLulZ9EGPyC61QAV8Cp92Lk',
    appId: '1:631517996189:web:4c77e3c47335889d26e074',
    messagingSenderId: '631517996189',
    projectId: 'todo-app-9bec6',
    authDomain: 'todo-app-9bec6.firebaseapp.com',
    storageBucket: 'todo-app-9bec6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBThFzAicyU3R_dajgiqlM_fyeqbKCdB8w',
    appId: '1:631517996189:android:d249a204f3f8154126e074',
    messagingSenderId: '631517996189',
    projectId: 'todo-app-9bec6',
    storageBucket: 'todo-app-9bec6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYQa-hDXmtU4EMm9Xl9SiJX5dVRZyrJpg',
    appId: '1:631517996189:ios:3362611b14d8fac526e074',
    messagingSenderId: '631517996189',
    projectId: 'todo-app-9bec6',
    storageBucket: 'todo-app-9bec6.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYQa-hDXmtU4EMm9Xl9SiJX5dVRZyrJpg',
    appId: '1:631517996189:ios:3362611b14d8fac526e074',
    messagingSenderId: '631517996189',
    projectId: 'todo-app-9bec6',
    storageBucket: 'todo-app-9bec6.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5Jh1gBPnFxLulZ9EGPyC61QAV8Cp92Lk',
    appId: '1:631517996189:web:dd131aa3027ef66026e074',
    messagingSenderId: '631517996189',
    projectId: 'todo-app-9bec6',
    authDomain: 'todo-app-9bec6.firebaseapp.com',
    storageBucket: 'todo-app-9bec6.appspot.com',
  );
}
